#
# Mica server main configuration file.
# See documentation at: http://wiki.obiba.org/display/MICADOC/Mica+Configuration+Files
#

# HTTP server configuration
server:
    port: 8082
    address: localhost

https:
    port: 8445

# Opal: data dictionaries, summaries and taxonomies
opal:
    url: https://localhost:8443
    username: administrator
    password: password

# Agate: user realm and application services configuration
agate:
    url: https://localhost:8444
    application:
        name: mica
        key: changeit

# Elasticsearch: search engine configuration
elasticsearch:
    dataNode: false
    clusterName: mica
    transportClient: true
    transportAddress: "localhost:9300"
    shards: 5
    replicas: 1
    settings: "http.enabled: false"
    maxConcurrentJoinQueries: 2
    concurrentJoinQueriesWaitTimeout: 15000

# Shiro: user directory configuration
shiro:
    password:
        nbHashIterations: 10000
        salt: mica

#
# Database connection
#

spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/mica
    profiles: prod
